# Generated by Django 3.2 on 2022-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
