# Generated by Django 3.2 on 2022-05-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0002_alter_mymodel_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='age',
        ),
    ]
